# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Rcpp function to calculate RMSE
#' @description A Rcpp function to calculate RMSE
#' @param Xhat the estimated matrix
#' @param X the origin data matrix
#' @param missnum the number of missing values in X_miss
#' @return the value of RMSE. Details see Section Simulation.
#' @examples
#' \dontrun{
#' X1<-matrix(rnorm(20*30),nrow=20,ncol=30)
#' X1hat<-matrix(rnorm(20*30),nrow=20,ncol=30)
#' missnum1<-10*10
#' rmse<-RMSEC(X1hat,X1,missnum1)
#' }
#' @export
RMSEC <- function(Xhat, X, missnum) {
    .Call('_finalwork_RMSEC', PACKAGE = 'finalwork', Xhat, X, missnum)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param a the first parameter in rbeta(a,b)
#' @param b the second parameter in rbeta(a,b)
#' @param n the parameter in rbinom(1,n,p)
#' @param initial the initial values of chain
#' @param N the number of samples
#' @return a random sample 
#' @examples
#' \dontrun{
#' N_0 <- 10000;burn <- 1000
#' a_0<-3;b_0<-4;n_0<-20
#' init<-c(sample(0:n_0,1),runif(1))
#' matC <- gibbsC(a_0,b_0,n_0,init,N_0)
#' }
#' @export
gibbsC <- function(a, b, n, initial, N) {
    .Call('_finalwork_gibbsC', PACKAGE = 'finalwork', a, b, n, initial, N)
}

